apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from Kubernetes Job"]
      restartPolicy: Never
