name: Jobnik Backend Builder
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
# Params
env:
  BUILD_PATH: docker.io/pavelzagalsky
  SERVICE_NAME: jobnik

jobs:
  build:
    name: Jobnik Backend Builder
    runs-on: ubuntu-latest
    steps:
      - name: Getting branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Checking out the branch "${{ steps.branch-names.outputs.current_branch }}"
        uses: actions/checkout@v4
        with:
            ref: ${{ steps.branch-names.outputs.current_branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Hub Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker latest image upon push to master
        if: ${{ github.event_name == 'push' && steps.branch-names.outputs.current_branch == 'master' }}
        run: |
          cd backend
          docker buildx build --push --platform linux/amd64 -t ${{ env.BUILD_PATH }}/${{ env.SERVICE_NAME }}:${{ github.sha }} -f Dockerfile .
          docker buildx build --push --platform linux/amd64 -t ${{ env.BUILD_PATH }}/${{ env.SERVICE_NAME }}:${{ steps.branch-names.outputs.current_branch }}-${{ github.run_number }} -f Dockerfile .

      - name: Build and push docker latest image upon workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          cd backend
          docker buildx build --push --platform linux/amd64 -t ${{ env.BUILD_PATH }}/${{ env.SERVICE_NAME }}:${{ steps.branch-names.outputs.current_branch }}-${{ github.run_number }} -f Dockerfile .

      - name: Deployment summary
        run: |
          echo Branch: ${{ steps.branch-names.outputs.current_branch }}
          echo Service: ${{ env.SERVICE_NAME }}
          echo Docker Hub: ${{ env.BUILD_PATH }}/${{ env.SERVICE_NAME }}:${{ steps.branch-names.outputs.current_branch }}-${{ github.run_number }}
          echo Image: ${{ env.SERVICE_NAME }}:${{ steps.branch-names.outputs.current_branch }}-${{ github.run_number }}